# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b5b0bf75ac83a6148b58d90eb433acf02d13c00b69682b1bf84c8c09c9afb9298b5dab83c078076e7bf4561f369feeda4a300bb03e2fe520eaac404dd2498f7

test:
  secret_key_base: ac7498403d2ec332e329b5f0bf66ffd10ea20b7b8b687af1fe08c5ca85e9dd3eb022b33679485d971d41119a19e0d5f2d5d10b55bfd41250a1ac45b0f9e78229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
